### ISSUE TITLE
Appreciate your work, created a little something inspired by you.

### ISSUE THREAD

**Issue by zetjiin** [syorito-hatsuki/yet-another-cobble-gen#12]
Hey man. I really liked the way one can add custom generators, and so I created this to help people who want to create their own generators: https://github.com/zetjiin/yacg-python-custom-generators-script
Feel free to incorporate it however you like, but I made my proposition by Pull Request. 
Thanks for the mod and appreciate the work.

**Comment by syorito-hatsuki** [comment]
Not bad, thanks. But why you using KubeJS instead of vanilla ways?

**Comment by zetjiin** [comment]
I couldn't get them to work, and that seemed faster then debugging.

**Comment by syorito-hatsuki** [comment]
That wasn't good🤔
New modpackers prefer DataPacks, so it will be good if you script can support both🤔

**Comment by zetjiin** [comment]
I see, well I tried by following your tutorial and since it mentioned kubejs I went that way,  I tried like 3 times with datapack before this, and I couldn't get minecraft to read recipies for some reason. Maybe I'll try again in the future,

**Comment by syorito-hatsuki** [comment]
> I see, well I tried by following your tutorial and since it mentioned kubejs I went that way, I tried like 3 times with datapack before this, and I couldn't get minecraft to read recipies for some reason. Maybe I'll try again in the future,

I will later try myself on my tutorial and send you working structure ZIP

**Comment by syorito-hatsuki** [comment]
[Archive.tar.gz](https://github.com/syorito-hatsuki/yet-another-cobble-gen/files/13302696/Archive.tar.gz)
Here is bedrock generator as example
