### ISSUE TITLE
Breaking Block With Large Content

### ISSUE THREAD

**Issue by 5cript** [syorito-hatsuki/yet-another-cobble-gen#14]
What happens when I break the block when it has 400k items inside?
I am currently deleting all items via trashcan, but I need to know if I kill my world in case of an accident.

**Comment by syorito-hatsuki** [comment]
400 for Minecraft should be like nothing🤔, but I will test at home. Last week I played ATM7 and broke Barrel with 2M cobblestone and it just drop to 30 FPS on my PC. World can be always fixed from that by starting server and write `kill @e[type=minecraft:item]` it will be kill all item entities on ground, that how forks ClearLag and other mods/plugins.

**Comment by syorito-hatsuki** [comment]
But who u stored 400k if generator max stack per slot is 64 item and max slot count is 255 so whole generator can only contain 16k🤔🤔🤔

**Comment by 5cript** [comment]
> 400 for Minecraft should be like nothing🤔, but I will test at home. Last week I played ATM7 and broke Barrel with 2M cobblestone and it just drop to 30 FPS on my PC. World can be always fixed from that by starting server and write `kill @e[type=minecraft:item]` it will be kill all item entities on ground, that how forks ClearLag and other mods/plugins.

You are right, the stacking actually prevents the game from dying. I still have anxiety from older days.

> But who u stored 400k if generator max stack per slot is 64 item and max slot count is 255 so whole generator can only contain 16k🤔🤔🤔

The block inspection mod shows (the fabric equivalent of WAILA) me the numbers, I unfortunately cannot make a screenshot anymore, except by reproducing it. Same number were on the floor after breaking the block.

**Comment by syorito-hatsuki** [comment]
> > 400 for Minecraft should be like nothing🤔, but I will test at home. Last week I played ATM7 and broke Barrel with 2M cobblestone and it just drop to 30 FPS on my PC. World can be always fixed from that by starting server and write `kill @e[type=minecraft:item]` it will be kill all item entities on ground, that how forks ClearLag and other mods/plugins.
> 
> You are right, the stacking actually prevents the game from dying. I still have anxiety from older days.
> 
> > But who u stored 400k if generator max stack per slot is 64 item and max slot count is 255 so whole generator can only contain 16k🤔🤔🤔
> 
> The block inspection mod shows (the fabric equivalent of WAILA) me the numbers, I unfortunately cannot make a screenshot anymore, except by reproducing it. Same number were on the floor after breaking the block.

Just from interest, what generator u used and did block stored in generator?

**Comment by 5cript** [comment]
Stone generator and stone
