### ISSUE TITLE
Suggestion: adding a power requirement option to generators

### ISSUE THREAD

**Issue by Wizardon777** [syorito-hatsuki/yet-another-cobble-gen#15]
Hi! first of all love your work!

I'm working on a Skyblock 1.20.1 modpack, and as the title says, I have a suggestion/request.
in order to "lock" the use of the generators to mid game, it'd be a nice option to require power usage.

keep up the good work!

**Comment by syorito-hatsuki** [comment]
I tried one time make it work with energy, but idk why I stop did it. I will try again when I have free time (not in next 2 weeks)

**Comment by syorito-hatsuki** [comment]
@Wizardon777 

# 2024.5.2
* Added Ducky Updater Lib
* Added Energy Support
    * Added Energy Free Upgrade
* Increase stack size per item from 99 to 1024
* Updated fStats

> 1.20-1.20.4 https://modrinth.com/mod/yacg/version/XeMLW7c6
> 1.20.5+ https://modrinth.com/mod/yacg/version/2024.5.2
