### ISSUE TITLE
Minecraft not loading with version 2024.5.2

### ISSUE THREAD

**Issue by Wizardon777** [syorito-hatsuki/yet-another-cobble-gen#16]
Hello!
Minecraft is simply not loading with the new update (which is weird), no crash, no log, 
it just closes a few seconds after I click the Play button
![Capture](https://github.com/syorito-hatsuki/yet-another-cobble-gen/assets/22551232/356b63c0-7318-42af-aeee-367f278f47f4)
I do have a lot (over 250) other mods installed, but the only change is updating YACG.

as soon as I revert to the older version, everything works again.

Minecraft 1.20.1
Fabric 0.15.11

and thank you for considering my earlier suggestion :)

**Comment by syorito-hatsuki** [comment]
Try over [Prism Launcher](https://prismlauncher.org), it gives better logs

**Comment by syorito-hatsuki** [comment]
![image](https://github.com/syorito-hatsuki/yet-another-cobble-gen/assets/33298273/55721683-32ca-4267-ab1b-a5887b695fb2)
I tried downloading and it looks like it works fine. Should be a problem with our launcher

**Comment by Wizardon777** [comment]
Got a log, kinda, the last thing it said before "disappearing" minecraft is:
[20:45:02] [Render thread/ERROR]: config\yacg\generators.json -> config\yacg\backup_generators.json: The destination file already exists.

so I deleted the file and minecraft loaded!

**Comment by syorito-hatsuki** [comment]
> Got a log, kinda, the last thing it said before "disappearing" minecraft is: [20:45:02] [Render thread/ERROR]: config\yacg\generators.json -> config\yacg\backup_generators.json: The destination file already exists.
> 
> so I deleted the file and minecraft loaded!

Oh, interesting, I think it can be a Windows-only problem. I use Linux and it just overrides it in my environment.

I will add next time additional unique text for backup files, but only, if I have a new request or have my reason to make an update 

**_By my plans, the next content update will be in 2024 Q4_**
