### ISSUE TITLE
I am unable to craft any item from this mod.

### ISSUE THREAD

**Issue by NavonodAU** [syorito-hatsuki/yet-another-cobble-gen#19]
I can't craft the generators or the upgrades, and EMI doesn't show the crafting recipes.

**Comment by syorito-hatsuki** [comment]
Mod version 
Minecraft Version 
Log file

**Comment by syorito-hatsuki** [comment]
Ouch, I maybe know why. Thanks Mojang...

**Comment by NavonodAU** [comment]
Latest version 2024.6.1, and 1.21. I tried it with just REI also.
[latest.log](https://github.com/user-attachments/files/15893765/latest.log)

**Comment by syorito-hatsuki** [comment]
Should be fine now
https://modrinth.com/mod/yacg/version/2024.6.2
