### ISSUE TITLE
bring 1.20 features to 1.19.2

### ISSUE THREAD

**Issue by dekub100** [syorito-hatsuki/yet-another-cobble-gen#5]
by features i mean upgrades and crafting, tried to do it myself but couldnt do it
would be forever grateful

**Comment by syorito-hatsuki** [comment]
Oh. I only just realized that my mod favorite versions are 1.20+ and 1.19.2 :)

Alright. I will port in next week.

**Comment by syorito-hatsuki** [comment]
# 2023.7.1
* Backport from 1.20+ to 1.19.2
> https://modrinth.com/mod/yacg/version/zvo1Dk6Y
